#
# CI Pipeline
#

# NOTES:
# This workflow builds and tests extension updates.

name: Build
on:
  push:
    branches: [main, 'release/*']
  pull_request:
    branches: [main, 'release/*']
  workflow_dispatch:

permissions: {}

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Install dependencies
        shell: pwsh
        timeout-minutes: 3
        run: ./scripts/pipeline-deps.ps1

      - name: Build module
        shell: pwsh
        timeout-minutes: 5
        run: Invoke-Build -Configuration Release

      - name: Upload official extension
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: Extension-official
          path: ./out/extension/ps-rule.*
          retention-days: 3
          if-no-files-found: error

      - name: Upload non-official extension
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: Extension-non-official
          path: ./out/extension/bewhite.*
          retention-days: 3
          if-no-files-found: error
