#
# CI Pipeline
#

# NOTES:
# This workflow builds and tests extension updates.

name: Build
on:
  push:
    branches: [main, 'release/*']
  pull_request:
    branches: [main, 'release/*']
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        shell: pwsh
        timeout-minutes: 3
        run: ./scripts/pipeline-deps.ps1

      - name: Build module
        shell: pwsh
        timeout-minutes: 5
        run: Invoke-Build -Configuration Release

      - name: Upload official extension
        uses: actions/upload-artifact@v4
        with:
          name: Extension-official
          path: ./out/extension/ps-rule.*
          retention-days: 3
          if-no-files-found: error

      - name: Upload non-official extension
        uses: actions/upload-artifact@v4
        with:
          name: Extension-non-official
          path: ./out/extension/bewhite.*
          retention-days: 3
          if-no-files-found: error
