#
# CI Pipeline
#

# NOTES:
# This workflow builds and tests extension updates.

name: Build
on:
  push:
    branches: [ main, 'release/*' ]
  pull_request:
    branches: [ main, 'release/*' ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

    - name: Checkout
      uses: actions/checkout@v3


    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      shell: pwsh
      timeout-minutes: 3
      run: ./scripts/pipeline-deps.ps1

    - name: Build module
      shell: pwsh
      timeout-minutes: 5
      run: Invoke-Build -Configuration Release

    - name: Upload extension
      uses: actions/upload-artifact@v3
      with:
        name: Extension
        path: ./out/extension/*
        retention-days: 3
        if-no-files-found: error
