#
# Stale issues
#
name: Close stale issues
on:
  schedule:
    - cron: '30 1 * * *'

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs within 7 days.
            Thank you for your contributions.

          close-issue-message: This issue was closed because it has not had any recent activity.

          days-before-stale: 14
          days-before-pr-stale: -1

          days-before-close: 7
          days-before-pr-close: -1

          any-of-labels: 'question,duplicate,incomplete,waiting-feedback'
          stale-issue-label: stale
